version: "3"

services:
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: application
  node:
    image: node:latest
    working_dir: /code
    volumes:
      - "./:/code"
    depends_on:
      - mysql
    command: "sleep infinity"